name: x86 Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-x86:
    runs-on: ubuntu-latest  #  x86_64 runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Compile with g++
        run: |
          g++ -mavx -mfma -O2 -march=native -c crm_mth.cpp
